server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ah-fanfan/springcloud.git
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
